version: '2.3'
services:
  mysql:
    image: mysql:5.7.20
    container_name: wso2ei-mysql
    ports:
      - 3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: WSO2_EI_ANALYTICS_DB
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 60s
      retries: 5
  wso2ei-analytics-worker:
    image: wso2/wso2ei-analytics-worker:6.5.0
    container_name: wso2ei-analytics-worker
    ports:
      - 9091:9091
      - 9444:9444
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9444"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 70s
    volumes:
      # mounting configurations
      - ./worker:/home/wso2carbon/wso2-config-volume
    depends_on:
      mysql:
        condition: service_healthy
  wso2ei-analytics-dashboard:
    image: wso2/wso2ei-analytics-dashboard:6.5.0
    container_name: wso2ei-analytics-dashboard
    ports:
      - 9643:9643
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9643"]
      interval: 10s
      timeout: 120s
      retries: 5
      start_period: 70s
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./dashboard:/home/wso2carbon/wso2-config-volume
  wso2ei-integrator:
    image: wso2/wso2ei-integrator:6.5.0
    container_name: wso2ei-integrator
    ports:
      - 9443:9443
      - 8243:8243
      - 8280:8280
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:9443/carbon/admin/login.jsp"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 100s
    volumes:
      # mounting configurations
      - ./integrator:/home/wso2carbon/wso2-config-volume/
    depends_on:
      mysql:
        condition: service_healthy
      wso2ei-analytics-worker:
        condition: service_healthy
      wso2ei-analytics-dashboard:
        condition: service_healthy
